{% set name = "catkin_pkg" %}
{% set version = "1.0.0" %}
{% set sha256 = "48e88c995838807165bb70c6272abab2d6dda5efc210f62db8ac714d4c96a0c6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ros-infrastructure/catkin_pkg/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - fix-multiple-pkgs.patch

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 1
  noarch: python
  entry_points:
    - catkin_create_pkg = catkin_pkg.cli.create_pkg:main
    - catkin_find_pkg = catkin_pkg.cli.find_pkg:main
    - catkin_generate_changelog = catkin_pkg.cli.generate_changelog:main_catching_runtime_error
    - catkin_package_version = catkin_pkg.cli.package_version:main
    - catkin_prepare_release = catkin_pkg.cli.prepare_release:main
    - catkin_tag_changelog = catkin_pkg.cli.tag_changelog:main
    - catkin_test_changelog = catkin_pkg.cli.test_changelog:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - docutils
    - python-dateutil
    - pyparsing >=1.5.7

test:
  requires:
    - python {{ python_min }}
  commands:
    - catkin_create_pkg --help
    - catkin_find_pkg --help
    - catkin_generate_changelog --help
    - catkin_package_version --help
    - catkin_prepare_release --help
    - catkin_tag_changelog --help
    - catkin_test_changelog --help
  imports:
    - catkin_pkg

about:
  home: http://wiki.ros.org/catkin_pkg
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Standalone Python library for the catkin build system.
  dev_url: https://github.com/ros-infrastructure/catkin_pkg

extra:
  recipe-maintainers:
    - wolfv
    - seanyen
    - Tobias-Fischer
