{% set name = "catkin_pkg" %}
{% set version = "0.4.17" %}
{% set sha256 = "ce7adfc4a8393e10339abb3eb99c0e674e853a10b2431919b2eab1ba0f9628c5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ros-infrastructure/catkin_pkg/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  noarch: python
  entry_points:
    - catkin_create_pkg = catkin_pkg.cli.create_pkg:main
    - catkin_find_pkg = catkin_pkg.cli.find_pkg:main
    - catkin_generate_changelog = catkin_pkg.cli.generate_changelog:main_catching_runtime_error
    - catkin_package_version = catkin_pkg.cli.package_version:main
    - catkin_prepare_release = catkin_pkg.cli.prepare_release:main
    - catkin_tag_changelog = catkin_pkg.cli.tag_changelog:main
    - catkin_test_changelog = catkin_pkg.cli.test_changelog:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - docutils
    - python-dateutil
    - pyparsing >=1.5.7

test:
  commands:
    - catkin_create_pkg --help
    - catkin_find_pkg --help
    - catkin_generate_changelog --help
    - catkin_package_version --help
    - catkin_prepare_release --help
    - catkin_tag_changelog --help
    - catkin_test_changelog --help
  imports:
    - catkin_pkg

about:
  home: http://wiki.ros.org/catkin_pkg
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Standalone Python library for the catkin build system.
  dev_url: https://github.com/ros-infrastructure/catkin_pkg

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - seanyen
